// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xomvanapvfsycnvwcows.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvbXZhbmFwdmZzeWNudndjb3dzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MjcyMTUsImV4cCI6MjA2MTQwMzIxNX0.N3SmzdHUMMHVDMSdD5bS-AEhzlk9vxwa_7UBQTHd_xU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);